name: Build & Release Pdf2ImgApp

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Download and setup Poppler for Windows
      run: |
        curl -L -o poppler.zip https://github.com/oschwartz10612/poppler-windows/releases/latest/download/poppler-23.11.0-x86_64.zip
        tar -xf poppler.zip
        echo "$PWD/poppler-23.11.0/Library/bin" >> $GITHUB_PATH

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name Pdf2ImgApp src/gui/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Pdf2ImgApp
        path: dist/Pdf2ImgApp.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Pdf2ImgApp.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
