name: Build & Release Pdf2ImgApp

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/windows-build-reusable.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download built executable
      uses: actions/download-artifact@v4
      with:
        name: Pdf2Img

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: pdf2img.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
