name: Build Windows Executable

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Download and setup Poppler for Windows
      run: |
        curl -L -o poppler.zip https://github.com/oschwartz10612/poppler-windows/releases/latest/download/poppler-23.11.0-x86_64.zip
        tar -xf poppler.zip
        echo "$PWD/poppler-23.11.0/Library/bin" >> $GITHUB_PATH

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name Pdf2ImgApp src/gui/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pdf2ImgApp
        path: dist/Pdf2ImgApp.exe
