name: Build Windows Executable (Reusable)

on:
  workflow_call:  # Allows other workflows to call this

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Download and setup Poppler for Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/oschwartz10612/poppler-windows/releases/download/v24.08.0-0/Release-24.08.0-0.zip" -OutFile "poppler.zip"
        Expand-Archive -Path "poppler.zip" -DestinationPath "poppler"
        "$pwd\poppler\Library\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Remove-Item "poppler.zip"
      shell: pwsh

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name Pdf2ImgApp src/gui/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pdf2ImgApp
        path: dist/Pdf2ImgApp.exe
